export default {
  groups: {
    1: { id: 1, name: 'pink' },
    2: { id: 2, name: 'purple' },
    3: { id: 3, name: 'red' },
    4: { id: 4, name: 'orange' },
    5: { id: 5, name: 'yellow' },
    6: { id: 6, name: 'green' },
    7: { id: 7, name: 'cyan' },
    8: { id: 8, name: 'blue' },
    9: { id: 9, name: 'brown' },
    10: { id: 10, name: 'white' },
    11: { id: 11, name: 'grey' },
  },
  /*
   * Color name is a UUID as CSS Specification maps names to hex codes
   */
  colors: {
    pink: {
      name: 'Pink',
      hex: '#FFC0CB',
      shades: [],
      mix: [],
      groupId: 1,
    },
    lightPink: {
      name: 'LightPink',
      hex: '#FFB6C1',
      shades: [],
      mix: [],
      groupId: 1,
    },
    hotPink: {
      name: 'HotPink',
      hex: '#FF69B4',
      shades: [],
      mix: [],
      groupId: 1,
    },
    deepPink: {
      name: 'DeepPink',
      hex: '#FF1493',
      shades: [],
      mix: [],
      groupId: 1,
    },
    paleVioletRed: {
      name: 'PaleVioletRed',
      hex: '#DB7093',
      shades: [],
      mix: [],
      groupId: 1,
    },
    mediumVioletRed: {
      name: 'MediumVioletRed',
      hex: '#C71585',
      shades: [],
      mix: [],
      groupId: 'pink',
    },
    lavender: {
      name: 'Lavender',
      hex: '#E6E6FA',
      shades: [],
      mix: [],
      groupId: 2,
    },
    thistle: {
      name: 'Thistle',
      hex: '#D8BFD8',
      shades: [],
      mix: [],
      groupId: 2,
    },
    plum: {
      name: 'Plum',
      hex: '#DDA0DD',
      shades: [],
      mix: [],
      groupId: 2,
    },
    orchid: {
      name: 'Orchid',
      hex: '#DA70D6',
      shades: [],
      mix: [],
      groupId: 2,
    },
    violet: {
      name: 'Violet',
      hex: '#EE82EE',
      shades: [],
      mix: [],
      groupId: 2,
    },
    fuchsia: {
      name: 'Fuchsia',
      hex: '#FF00FF',
      shades: [],
      mix: [],
      groupId: 2,
    },
    magenta: {
      name: 'Magenta',
      hex: '#FF00FF',
      shades: [],
      mix: [],
      groupId: 2,
    },
    mediumOrchid: {
      name: 'MediumOrchid',
      hex: '#BA55D3',
      shades: [],
      mix: [],
      groupId: 2,
    },
    darkOrchid: {
      name: 'DarkOrchid',
      hex: '#9932CC',
      shades: [],
      mix: [],
      groupId: 2,
    },
    darkViolet: {
      name: 'DarkViolet',
      hex: '#9400D3',
      shades: [],
      mix: [],
      groupId: 2,
    },
    blueViolet: {
      name: 'BlueViolet',
      hex: '#8A2BE2',
      shades: [],
      mix: [],
      groupId: 2,
    },
    darkMagenta: {
      name: 'DarkMagenta',
      hex: '#8B008B',
      shades: [],
      mix: [],
      groupId: 2,
    },
    purple: {
      name: 'Purple',
      hex: '#800080',
      shades: [],
      mix: [],
      groupId: 2,
    },
    mediumPurple: {
      name: 'MediumPurple',
      hex: '#9370DB',
      shades: [],
      mix: [],
      groupId: 2,
    },
    mediumSlateBlue: {
      name: 'MediumSlateBlue',
      hex: '#7B68EE',
      shades: [],
      mix: [],
      groupId: 2,
    },
    slateBlue: {
      name: 'SlateBlue',
      hex: '#6A5ACD',
      shades: [],
      mix: [],
      groupId: 2,
    },
    darkSlateBlue: {
      name: 'DarkSlateBlue',
      hex: '#483D8B',
      shades: [],
      mix: [],
      groupId: 2,
    },
    rebeccaPurple: {
      name: 'RebeccaPurple',
      hex: '#663399',
      shades: [],
      mix: [],
      groupId: 2,
    },
    indigo: {
      name: 'Indigo',
      hex: '#4B0082',
      shades: [],
      mix: [],
      groupId: 2,
    },

    lightSalmon: {
      name: 'LightSalmon',
      hex: '#FFA07A',
      shades: [],
      mix: [],
      groupId: 3,
    },
    salmon: {
      name: 'Salmon',
      hex: '#FA8072',
      shades: [],
      mix: [],
      groupId: 3,
    },
    darkSalmon: {
      name: 'DarkSalmon',
      hex: '#E9967A',
      shades: [],
      mix: [],
      groupId: 3,
    },
    lightCoral: {
      name: 'LightCoral',
      hex: '#F08080',
      shades: [],
      mix: [],
      groupId: 3,
    },
    indianRed: {
      name: 'IndianRed',
      hex: '#CD5C5C',
      shades: [],
      mix: [],
      groupId: 3,
    },
    crimson: {
      name: 'Crimson',
      hex: '#DC143C',
      shades: [],
      mix: [],
      groupId: 3,
    },
    red: {
      name: 'Red',
      hex: '#FF0000',
      shades: [],
      mix: [],
      groupId: 3,
    },
    fireBrick: {
      name: 'FireBrick',
      hex: '#B22222',
      shades: [],
      mix: [],
      groupId: 3,
    },
    darkRed: {
      name: 'DarkRed',
      hex: '#8B0000',
      shades: [],
      mix: [],
      groupId: 3,
    },
    orange: {
      name: 'Orange',
      hex: '#FFA500',
      shades: [],
      mix: [],
      groupId: 4,
    },
    darkOrange: {
      name: 'DarkOrange',
      hex: '#FF8C00',
      shades: [],
      mix: [],
      groupId: 4,
    },
    coral: {
      name: 'Coral',
      hex: '#FF7F50',
      shades: [],
      mix: [],
      groupId: 4,
    },
    tomato: {
      name: 'Tomato',
      hex: '#FF6347',
      shades: [],
      mix: [],
      groupId: 4,
    },
    orangeRed: {
      name: 'OrangeRed',
      hex: '#FF4500',
      shades: [],
      mix: [],
      groupId: 4,
    },

    gold: {
      name: 'Gold',
      hex: '#FFD700',
      shades: [],
      mix: [],
      groupId: 5,
    },
    yellow: {
      name: 'Yellow',
      hex: '#FFFF00',
      shades: [],
      mix: [],
      groupId: 5,
    },
    lightYellow: {
      name: 'LightYellow',
      hex: '#FFFFE0',
      shades: [],
      mix: [],
      groupId: 5,
    },
    lemonChiffon: {
      name: 'LemonChiffon',
      hex: '#FFFACD',
      shades: [],
      mix: [],
      groupId: 5,
    },
    lightGoldenRodYellow: {
      name: 'LightGoldenRodYellow',
      hex: '#FAFAD2',
      shades: [],
      mix: [],
      groupId: 5,
    },
    papayaWhip: {
      name: 'PapayaWhip',
      hex: '#FFEFD5',
      shades: [],
      mix: [],
      groupId: 5,
    },
    moccasin: {
      name: 'Moccasin',
      hex: '#FFE4B5',
      shades: [],
      mix: [],
      groupId: 5,
    },
    peachPuff: {
      name: 'PeachPuff',
      hex: '#FFDAB9',
      shades: [],
      mix: [],
      groupId: 5,
    },
    paleGoldenRod: {
      name: 'PaleGoldenRod',
      hex: '#EEE8AA',
      shades: [],
      mix: [],
      groupId: 5,
    },
    khaki: {
      name: 'Khaki',
      hex: '#F0E68C',
      shades: [],
      mix: [],
      groupId: 5,
    },
    darkKhaki: {
      name: 'DarkKhaki',
      hex: '#BDB76B',
      shades: [],
      mix: [],
      groupId: 5,
    },

    greenYellow: {
      name: 'GreenYellow',
      hex: '#ADFF2F',
      shades: [],
      mix: [],
      groupId: 6,
    },
    chartreuse: {
      name: 'Chartreuse',
      hex: '#7FFF00',
      shades: [],
      mix: [],
      groupId: 6,
    },
    lawnGreen: {
      name: 'LawnGreen',
      hex: '#7CFC00',
      shades: [],
      mix: [],
      groupId: 6,
    },
    lime: {
      name: 'Lime',
      hex: '#00FF00',
      shades: [],
      mix: [],
      groupId: 6,
    },
    limeGreen: {
      name: 'LimeGreen',
      hex: '#32CD32',
      shades: [],
      mix: [],
      groupId: 6,
    },
    paleGreen: {
      name: 'PaleGreen',
      hex: '#98FB98',
      shades: [],
      mix: [],
      groupId: 6,
    },
    lightGreen: {
      name: 'LightGreen',
      hex: '#90EE90',
      shades: [],
      mix: [],
      groupId: 6,
    },
    mediumSpringGreen: {
      name: 'MediumSpringGreen',
      hex: '#00FA9A',
      shades: [],
      mix: [],
      groupId: 6,
    },
    springGreen: {
      name: 'SpringGreen',
      hex: '#00FF7F',
      shades: [],
      mix: [],
      groupId: 6,
    },
    mediumSeaGreen: {
      name: 'MediumSeaGreen',
      hex: '#3CB371',
      shades: [],
      mix: [],
      groupId: 6,
    },
    seaGreen: {
      name: 'SeaGreen',
      hex: '#2E8B57',
      shades: [],
      mix: [],
      groupId: 6,
    },
    forestGreen: {
      name: 'ForestGreen',
      hex: '#228B22',
      shades: [],
      mix: [],
      groupId: 6,
    },
    green: {
      name: 'Green',
      hex: '#008000',
      shades: [],
      mix: [],
      groupId: 6,
    },
    darkGreen: {
      name: 'DarkGreen',
      hex: '#006400',
      shades: [],
      mix: [],
      groupId: 6,
    },
    yellowGreen: {
      name: 'YellowGreen',
      hex: '#9ACD32',
      shades: [],
      mix: [],
      groupId: 6,
    },
    oliveDrab: {
      name: 'OliveDrab',
      hex: '#6B8E23',
      shades: [],
      mix: [],
      groupId: 6,
    },
    darkOliveGreen: {
      name: 'DarkOliveGreen',
      hex: '#556B2F',
      shades: [],
      mix: [],
      groupId: 6,
    },
    mediumAquaMarine: {
      name: 'MediumAquaMarine',
      hex: '#66CDAA',
      shades: [],
      mix: [],
      groupId: 6,
    },
    darkSeaGreen: {
      name: 'DarkSeaGreen',
      hex: '#8FBC8F',
      shades: [],
      mix: [],
      groupId: 6,
    },
    lightSeaGreen: {
      name: 'LightSeaGreen',
      hex: '#20B2AA',
      shades: [],
      mix: [],
      groupId: 6,
    },
    darkCyan: {
      name: 'DarkCyan',
      hex: '#008B8B',
      shades: [],
      mix: [],
      groupId: 6,
    },
    teal: {
      name: 'Teal',
      hex: '#008080',
      shades: [],
      mix: [],
      groupId: 6,
    },

    aqua: {
      name: 'Aqua',
      hex: '#00FFFF',
      shades: [],
      mix: [],
      groupId: 7,
    },
    cyan: {
      name: 'Cyan',
      hex: '#00FFFF',
      shades: [],
      mix: [],
      groupId: 7,
    },
    lightCyan: {
      name: 'LightCyan',
      hex: '#E0FFFF',
      shades: [],
      mix: [],
      groupId: 7,
    },
    paleTurquoise: {
      name: 'PaleTurquoise',
      hex: '#AFEEEE',
      shades: [],
      mix: [],
      groupId: 7,
    },
    aquamarine: {
      name: 'Aquamarine',
      hex: '#7FFFD4',
      shades: [],
      mix: [],
      groupId: 7,
    },
    turquoise: {
      name: 'Turquoise',
      hex: '#40E0D0',
      shades: [],
      mix: [],
      groupId: 7,
    },
    mediumTurquoise: {
      name: 'MediumTurquoise',
      hex: '#48D1CC',
      shades: [],
      mix: [],
      groupId: 7,
    },
    darkTurquoise: {
      name: 'DarkTurquoise',
      hex: '#00CED1',
      shades: [],
      mix: [],
      groupId: 7,
    },

    cadetBlue: {
      name: 'CadetBlue',
      hex: '#5F9EA0',
      shades: [],
      mix: [],
      groupId: 8,
    },
    steelBlue: {
      name: 'SteelBlue',
      hex: '#4682B4',
      shades: [],
      mix: [],
      groupId: 8,
    },
    lightSteelBlue: {
      name: 'LightSteelBlue',
      hex: '#B0C4DE',
      shades: [],
      mix: [],
      groupId: 8,
    },
    lightBlue: {
      name: 'LightBlue',
      hex: '#ADD8E6',
      shades: [],
      mix: [],
      groupId: 8,
    },
    powderBlue: {
      name: 'PowderBlue',
      hex: '#B0E0E6',
      shades: [],
      mix: [],
      groupId: 8,
    },
    lightSkyBlue: {
      name: 'LightSkyBlue',
      hex: '#87CEFA',
      shades: [],
      mix: [],
      groupId: 8,
    },
    skyBlue: {
      name: 'SkyBlue',
      hex: '#87CEEB',
      shades: [],
      mix: [],
      groupId: 8,
    },
    cornflowerBlue: {
      name: 'CornflowerBlue',
      hex: '#6495ED',
      shades: [],
      mix: [],
      groupId: 8,
    },
    deepSkyBlue: {
      name: 'DeepSkyBlue',
      hex: '#00BFFF',
      shades: [],
      mix: [],
      groupId: 8,
    },
    dodgerBlue: {
      name: 'DodgerBlue',
      hex: '#1E90FF',
      shades: [],
      mix: [],
      groupId: 8,
    },
    royalBlue: {
      name: 'RoyalBlue',
      hex: '#4169E1',
      shades: [],
      mix: [],
      groupId: 8,
    },
    blue: {
      name: 'Blue',
      hex: '#0000FF',
      shades: [],
      mix: [],
      groupId: 8,
    },
    mediumBlue: {
      name: 'MediumBlue',
      hex: '#0000CD',
      shades: [],
      mix: [],
      groupId: 8,
    },
    darkBlue: {
      name: 'DarkBlue',
      hex: '#00008B',
      shades: [],
      mix: [],
      groupId: 8,
    },
    navy: {
      name: 'Navy',
      hex: '#000080',
      shades: [],
      mix: [],
      groupId: 8,
    },
    midnightBlue: {
      name: 'MidnightBlue',
      hex: '#191970',
      shades: [],
      mix: [],
      groupId: 8,
    },

    cornsilk: {
      name: 'Cornsilk',
      hex: '#FFF8DC',
      shades: [],
      mix: [],
      groupId: 9,
    },
    blanchedAlmond: {
      name: 'BlanchedAlmond',
      hex: '#FFEBCD',
      shades: [],
      mix: [],
      groupId: 9,
    },
    bisque: {
      name: 'Bisque',
      hex: '#FFE4C4',
      shades: [],
      mix: [],
      groupId: 9,
    },
    navajoWhite: {
      name: 'NavajoWhite',
      hex: '#FFDEAD',
      shades: [],
      mix: [],
      groupId: 9,
    },
    wheat: {
      name: 'Wheat',
      hex: '#F5DEB3',
      shades: [],
      mix: [],
      groupId: 9,
    },
    burlyWood: {
      name: 'BurlyWood',
      hex: '#DEB887',
      shades: [],
      mix: [],
      groupId: 9,
    },
    tan: {
      name: 'Tan',
      hex: '#D2B48C',
      shades: [],
      mix: [],
      groupId: 9,
    },
    rosyBrown: {
      name: 'RosyBrown',
      hex: '#BC8F8F',
      shades: [],
      mix: [],
      groupId: 9,
    },
    sandyBrown: {
      name: 'SandyBrown',
      hex: '#F4A460',
      shades: [],
      mix: [],
      groupId: 9,
    },
    goldenRod: {
      name: 'GoldenRod',
      hex: '#DAA520',
      shades: [],
      mix: [],
      groupId: 9,
    },
    darkGoldenRod: {
      name: 'DarkGoldenRod',
      hex: '#B8860B',
      shades: [],
      mix: [],
      groupId: 9,
    },
    peru: {
      name: 'Peru',
      hex: '#CD853F',
      shades: [],
      mix: [],
      groupId: 9,
    },
    chocolate: {
      name: 'Chocolate',
      hex: '#D2691E',
      shades: [],
      mix: [],
      groupId: 9,
    },
    olive: {
      name: 'Olive',
      hex: '#808000',
      shades: [],
      mix: [],
      groupId: 9,
    },
    saddleBrown: {
      name: 'SaddleBrown',
      hex: '#8B4513',
      shades: [],
      mix: [],
      groupId: 9,
    },
    sienna: {
      name: 'Sienna',
      hex: '#A0522D',
      shades: [],
      mix: [],
      groupId: 9,
    },
    brown: {
      name: 'Brown',
      hex: '#A52A2A',
      shades: [],
      mix: [],
      groupId: 9,
    },
    maroon: {
      name: 'Maroon',
      hex: '#800000',
      shades: [],
      mix: [],
      groupId: 9,
    },
    white: {
      name: 'White',
      hex: '#FFFFFF',
      shades: [],
      mix: [],
      groupId: 10,
    },
    snow: {
      name: 'Snow',
      hex: '#FFFAFA',
      shades: [],
      mix: [],
      groupId: 10,
    },
    honeyDew: {
      name: 'HoneyDew',
      hex: '#F0FFF0',
      shades: [],
      mix: [],
      groupId: 10,
    },
    mintCream: {
      name: 'MintCream',
      hex: '#F5FFFA',
      shades: [],
      mix: [],
      groupId: 10,
    },
    azure: {
      name: 'Azure',
      hex: '#F0FFFF',
      shades: [],
      mix: [],
      groupId: 10,
    },
    aliceBlue: {
      name: 'AliceBlue',
      hex: '#F0F8FF',
      shades: [],
      mix: [],
      groupId: 10,
    },
    ghostWhite: {
      name: 'GhostWhite',
      hex: '#F8F8FF',
      shades: [],
      mix: [],
      groupId: 10,
    },
    whiteSmoke: {
      name: 'WhiteSmoke',
      hex: '#F5F5F5',
      shades: [],
      mix: [],
      groupId: 10,
    },
    seaShell: {
      name: 'SeaShell',
      hex: '#FFF5EE',
      shades: [],
      mix: [],
      groupId: 10,
    },
    beige: {
      name: 'Beige',
      hex: '#F5F5DC',
      shades: [],
      mix: [],
      groupId: 10,
    },
    oldLace: {
      name: 'OldLace',
      hex: '#FDF5E6',
      shades: [],
      mix: [],
      groupId: 10,
    },
    floralWhite: {
      name: 'FloralWhite',
      hex: '#FFFAF0',
      shades: [],
      mix: [],
      groupId: 10,
    },
    ivory: {
      name: 'Ivory',
      hex: '#FFFFF0',
      shades: [],
      mix: [],
      groupId: 10,
    },
    antiqueWhite: {
      name: 'AntiqueWhite',
      hex: '#FAEBD7',
      shades: [],
      mix: [],
      groupId: 10,
    },
    linen: {
      name: 'Linen',
      hex: '#FAF0E6',
      shades: [],
      mix: [],
      groupId: 10,
    },
    lavenderBlush: {
      name: 'LavenderBlush',
      hex: '#FFF0F5',
      shades: [],
      mix: [],
      groupId: 10,
    },
    mistyRose: {
      name: 'MistyRose',
      hex: '#FFE4E1',
      shades: [],
      mix: [],
      groupId: 10,
    },
    gainsboro: {
      name: 'Gainsboro',
      hex: '#DCDCDC',
      shades: [],
      mix: [],
      groupId: 11,
    },
    lightGray: {
      name: 'LightGray',
      hex: '#D3D3D3',
      shades: [],
      mix: [],
      groupId: 11,
    },
    silver: {
      name: 'Silver',
      hex: '#C0C0C0',
      shades: [],
      mix: [],
      groupId: 11,
    },
    darkGray: {
      name: 'DarkGray',
      hex: '#A9A9A9',
      shades: [],
      mix: [],
      groupId: 11,
    },
    dimGray: {
      name: 'DimGray',
      hex: '#696969',
      shades: [],
      mix: [],
      groupId: 11,
    },
    gray: {
      name: 'Gray',
      hex: '#808080',
      shades: [],
      mix: [],
      groupId: 11,
    },
    lightSlateGray: {
      name: 'LightSlateGray',
      hex: '#778899',
      shades: [],
      mix: [],
      groupId: 11,
    },
    slateGray: {
      name: 'SlateGray',
      hex: '#708090',
      shades: [],
      mix: [],
      groupId: 11,
    },
    darkSlateGray: {
      name: 'DarkSlateGray',
      hex: '#2F4F4F',
      shades: [],
      mix: [],
      groupId: 11,
    },
    black: {
      name: 'Black',
      hex: '#000000',
      shades: [],
      mix: [],
      groupId: 11,
    },
  },
}
